### ISSUE TITLE
在macOS平台上编译报错

### ISSUE THREAD

**Issue by sh0rt2020** [betachen/tinychain#1]
macOS 10.13.5  
Xcode 9.4.1

用make指令编译链接的时候的时候报错如下：
```
Desktop/tinychain/include/tinychain/database.hpp:64:77: error: lambda
      capture 't' is not used [-Werror,-Wunused-lambda-capture]
  ...auto iter2 = std::find_if(tl.begin(), tl.end(), [&tx_hash, &t](const tx& t){
```
这个好像是苹果自带编译器的问题，陈老师这个问题是不是有方便的方法来解决啊？
我看到WebKit里面类似的错误好像是通过修改c++源码来解决的，但是c++我不熟悉，请求陈老师抽空看一下吧~

**Comment by betachen** [comment]
你好，修复了。
-Wunused-lambda-capture  选项要求不得存在没有使用的捕获变量，
在底下移除&t 的捕获就好了。

**Comment by sh0rt2020** [comment]
好的，O(∩_∩)O谢谢
