### ISSUE TITLE
I'm compiled failed too

### ISSUE THREAD

**Issue by DaZhaoGuo** [betachen/tinychain#9]
/usr/bin/cmake -H/home/gateway/bagguo/build/tinychain -B/home/gateway/bagguo/build/tinychain/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/gateway/bagguo/build/tinychain/build/CMakeFiles /home/gateway/bagguo/build/tinychain/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
make -f contrib/mongoose/CMakeFiles/mongoose_static.dir/build.make contrib/mongoose/CMakeFiles/mongoose_static.dir/depend
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
cd /home/gateway/bagguo/build/tinychain/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/gateway/bagguo/build/tinychain /home/gateway/bagguo/build/tinychain/contrib/mongoose /home/gateway/bagguo/build/tinychain/build /home/gateway/bagguo/build/tinychain/build/contrib/mongoose /home/gateway/bagguo/build/tinychain/build/contrib/mongoose/CMakeFiles/mongoose_static.dir/DependInfo.cmake --color=
Scanning dependencies of target mongoose_static
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
make -f contrib/mongoose/CMakeFiles/mongoose_static.dir/build.make contrib/mongoose/CMakeFiles/mongoose_static.dir/build
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
[  4%] Building C object contrib/mongoose/CMakeFiles/mongoose_static.dir/mongoose.c.o
cd /home/gateway/bagguo/build/tinychain/build/contrib/mongoose && /usr/bin/cc  -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMG_DISABLE_STDIO -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c11 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-strict-aliasing -g   -o CMakeFiles/mongoose_static.dir/mongoose.c.o   -c /home/gateway/bagguo/build/tinychain/contrib/mongoose/mongoose.c
[  8%] Linking C static library ../../lib/libmongoose.a
cd /home/gateway/bagguo/build/tinychain/build/contrib/mongoose && /usr/bin/cmake -P CMakeFiles/mongoose_static.dir/cmake_clean_target.cmake
cd /home/gateway/bagguo/build/tinychain/build/contrib/mongoose && /usr/bin/cmake -E cmake_link_script CMakeFiles/mongoose_static.dir/link.txt --verbose=1
/usr/bin/ar qc ../../lib/libmongoose.a  CMakeFiles/mongoose_static.dir/mongoose.c.o
/usr/bin/ranlib ../../lib/libmongoose.a
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
[  8%] Built target mongoose_static
make -f contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/build.make contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/depend
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
cd /home/gateway/bagguo/build/tinychain/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/gateway/bagguo/build/tinychain /home/gateway/bagguo/build/tinychain/contrib/jsoncpp /home/gateway/bagguo/build/tinychain/build /home/gateway/bagguo/build/tinychain/build/contrib/jsoncpp /home/gateway/bagguo/build/tinychain/build/contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/DependInfo.cmake --color=
Scanning dependencies of target jsoncpp_static
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
make -f contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/build.make contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/build
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
[ 12%] Building CXX object contrib/jsoncpp/CMakeFiles/jsoncpp_static.dir/jsoncpp.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/contrib/jsoncpp && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-deprecated-declarations -g   -o CMakeFiles/jsoncpp_static.dir/jsoncpp.cpp.o -c /home/gateway/bagguo/build/tinychain/contrib/jsoncpp/jsoncpp.cpp
[ 16%] Linking CXX static library ../../lib/libjsoncpp.a
cd /home/gateway/bagguo/build/tinychain/build/contrib/jsoncpp && /usr/bin/cmake -P CMakeFiles/jsoncpp_static.dir/cmake_clean_target.cmake
cd /home/gateway/bagguo/build/tinychain/build/contrib/jsoncpp && /usr/bin/cmake -E cmake_link_script CMakeFiles/jsoncpp_static.dir/link.txt --verbose=1
/usr/bin/ar qc ../../lib/libjsoncpp.a  CMakeFiles/jsoncpp_static.dir/jsoncpp.cpp.o
/usr/bin/ranlib ../../lib/libjsoncpp.a
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
[ 16%] Built target jsoncpp_static
make -f src/CMakeFiles/tinychain.dir/build.make src/CMakeFiles/tinychain.dir/depend
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
cd /home/gateway/bagguo/build/tinychain/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/gateway/bagguo/build/tinychain /home/gateway/bagguo/build/tinychain/src /home/gateway/bagguo/build/tinychain/build /home/gateway/bagguo/build/tinychain/build/src /home/gateway/bagguo/build/tinychain/build/src/CMakeFiles/tinychain.dir/DependInfo.cmake --color=
Scanning dependencies of target tinychain
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
make -f src/CMakeFiles/tinychain.dir/build.make src/CMakeFiles/tinychain.dir/build
make[2]: Entering directory '/home/gateway/bagguo/build/tinychain/build'
[ 20%] Building CXX object src/CMakeFiles/tinychain.dir/lib/exception/Instances.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/exception/Instances.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/exception/Instances.cpp
[ 25%] Building CXX object src/CMakeFiles/tinychain.dir/lib/exception/Exception.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/exception/Exception.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/exception/Exception.cpp
[ 29%] Building CXX object src/CMakeFiles/tinychain.dir/lib/exception/Error.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/exception/Error.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/exception/Error.cpp
[ 33%] Building CXX object src/CMakeFiles/tinychain.dir/lib/RestServ.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/RestServ.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/RestServ.cpp
[ 37%] Building CXX object src/CMakeFiles/tinychain.dir/lib/sha256.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/sha256.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/sha256.cpp
[ 41%] Building CXX object src/CMakeFiles/tinychain.dir/lib/logging.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/logging.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/logging.cpp
[ 45%] Building CXX object src/CMakeFiles/tinychain.dir/lib/utility/Stream_buf.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/utility/Stream_buf.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/utility/Stream_buf.cpp
[ 50%] Building CXX object src/CMakeFiles/tinychain.dir/lib/utility/Stream.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/utility/Stream.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/utility/Stream.cpp
[ 54%] Building CXX object src/CMakeFiles/tinychain.dir/lib/Mongoose.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/lib/Mongoose.cpp.o -c /home/gateway/bagguo/build/tinychain/src/lib/Mongoose.cpp
[ 58%] Building CXX object src/CMakeFiles/tinychain.dir/consensus.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/consensus.cpp.o -c /home/gateway/bagguo/build/tinychain/src/consensus.cpp
[ 62%] Building CXX object src/CMakeFiles/tinychain.dir/database.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/database.cpp.o -c /home/gateway/bagguo/build/tinychain/src/database.cpp
[ 66%] Building CXX object src/CMakeFiles/tinychain.dir/tinychain.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/tinychain.cpp.o -c /home/gateway/bagguo/build/tinychain/src/tinychain.cpp
[ 70%] Building CXX object src/CMakeFiles/tinychain.dir/commands.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/commands.cpp.o -c /home/gateway/bagguo/build/tinychain/src/commands.cpp
[ 75%] Building CXX object src/CMakeFiles/tinychain.dir/node.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/node.cpp.o -c /home/gateway/bagguo/build/tinychain/src/node.cpp
[ 79%] Building CXX object src/CMakeFiles/tinychain.dir/blockchain.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/blockchain.cpp.o -c /home/gateway/bagguo/build/tinychain/src/blockchain.cpp
[ 83%] Building CXX object src/CMakeFiles/tinychain.dir/network.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/network.cpp.o -c /home/gateway/bagguo/build/tinychain/src/network.cpp
[ 87%] Building CXX object src/CMakeFiles/tinychain.dir/main.cpp.o
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/c++   -DBOOST_NO_AUTO_PTR=1 -DBOOST_NO_TYPEID=1 -DMVS_DEBUG=1 -I/usr/local/include -I/home/gateway/bagguo/build/tinychain/contrib -I/home/gateway/bagguo/build/tinychain/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   -o CMakeFiles/tinychain.dir/main.cpp.o -c /home/gateway/bagguo/build/tinychain/src/main.cpp
[ 91%] Linking CXX executable ../bin/tinychain
cd /home/gateway/bagguo/build/tinychain/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/tinychain.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Werror -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Wno-deprecated-register -Wno-deprecated-declarations -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -g   CMakeFiles/tinychain.dir/lib/exception/Instances.cpp.o CMakeFiles/tinychain.dir/lib/exception/Exception.cpp.o CMakeFiles/tinychain.dir/lib/exception/Error.cpp.o CMakeFiles/tinychain.dir/lib/RestServ.cpp.o CMakeFiles/tinychain.dir/lib/sha256.cpp.o CMakeFiles/tinychain.dir/lib/logging.cpp.o CMakeFiles/tinychain.dir/lib/utility/Stream_buf.cpp.o CMakeFiles/tinychain.dir/lib/utility/Stream.cpp.o CMakeFiles/tinychain.dir/lib/Mongoose.cpp.o CMakeFiles/tinychain.dir/consensus.cpp.o CMakeFiles/tinychain.dir/database.cpp.o CMakeFiles/tinychain.dir/tinychain.cpp.o CMakeFiles/tinychain.dir/commands.cpp.o CMakeFiles/tinychain.dir/node.cpp.o CMakeFiles/tinychain.dir/blockchain.cpp.o CMakeFiles/tinychain.dir/network.cpp.o CMakeFiles/tinychain.dir/main.cpp.o  -o ../bin/tinychain -rdynamic /usr/local/lib/libboost_date_time.a ../lib/libjsoncpp.a ../lib/libmongoose.a -Wl,-Bstatic -lsqlite3 -Wl,-Bdynamic 
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): In function `unixDlError':
(.text+0x27fc1): undefined reference to `dlerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): In function `unixDlClose':
(.text+0x93f4): undefined reference to `dlclose'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): In function `unixDlSym':
(.text+0x9407): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): In function `unixDlOpen':
(.text+0x9419): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
src/CMakeFiles/tinychain.dir/build.make:516: recipe for target 'bin/tinychain' failed
make[2]: *** [bin/tinychain] Error 1
make[2]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
CMakeFiles/Makefile2:220: recipe for target 'src/CMakeFiles/tinychain.dir/all' failed
make[1]: *** [src/CMakeFiles/tinychain.dir/all] Error 2
make[1]: Leaving directory '/home/gateway/bagguo/build/tinychain/build'
Makefile:141: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DaZhaoGuo** [comment]
Here is enviroment info:
gateway@gateway001:/$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gateway@gateway001:/$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gateway@gateway001:/$ cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
gateway@gateway001:/$ more /etc/issue
Ubuntu 16.04.5 LTS \n \l

gateway@gateway001:/$ cat /proc/version
Linux version 4.4.0-134-generic (buildd@lgw01-amd64-033) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018

**Comment by betachen** [comment]
Just fixed, code committed already.
https://github.com/betachen/tinychain/commit/63854edadd80fc75117e94131edb1cc9a1c48a26

Missing 'dl' on ubuntu platform.
